package com.techtedapps.geminichat

import com.google.genai.client.GenerativeModel
import com.google.genai.common.HarmBlockThreshold
import com.google.genai.common.HarmCategory
import com.google.genai.common.SafetySetting

/**
 * Singleton object to configure and provide the GenerativeModel instance.
 *
 * This configuration applies highly permissive safety settings as requested (BLOCK_NONE for all categories).
 */
object Model {
    // The API key is now securely read from the BuildConfig, which is generated by Gradle
    // using the GEMINI_API_KEY environment variable provided by GitHub Secrets.
    private const val API_KEY = BuildConfig.GEMINI_API_KEY

    // Configuration to ensure "no restrictions" by setting all major harm categories to BLOCK_NONE.
    private val permissiveSafetySettings = listOf(
        // Set all core harm categories to BLOCK_NONE to disable filtering at the API level.
        SafetySetting(HarmCategory.HARASSMENT, HarmBlockThreshold.BLOCK_NONE),
        SafetySetting(HarmCategory.HATE_SPEECH, HarmBlockThreshold.BLOCK_NONE),
        SafetySetting(HarmCategory.SEXUALLY_EXPLICIT, HarmBlockThreshold.BLOCK_NONE),
        SafetySetting(HarmCategory.DANGEROUS_CONTENT, HarmBlockThreshold.BLOCK_NONE),
    )

    /**
     * Initializes the GenerativeModel with the 'gemini-2.5-flash' model
     * and the permissive safety settings.
     */
    val generativeModel: GenerativeModel = GenerativeModel(
        modelName = "gemini-2.5-flash",
        apiKey = API_KEY, // Reads the key from the secure BuildConfig field
        config = com.google.genai.client.GenerateContentConfig(
            safetySettings = permissiveSafetySettings
        )
    )
}


